services:
  sienge_main:
    build: .
    container_name: sienge_main
    env_file: scripts/.env
    volumes:
      - ./scripts:/scripts
    command: python /scripts/main.py

  api_customers:
    build: .
    container_name: api_customers
    env_file: scripts/.env
    volumes:
      - ./scripts:/scripts
    command: python /scripts/api_customers.py
    depends_on:
      - sienge_main   # opcional: só sobe depois do principal

  api_financialcategory:
    build: .
    container_name: api_financialcategory
    env_file: scripts/.env
    volumes:
      - ./scripts:/scripts
    command: python /scripts/api_financialCategory.py
    depends_on:
      - sienge_main

  sienge_refresh_mvw:
    build: .
    container_name: sienge_refresh_mvw
    env_file: scripts/.env
    volumes:
      - ./scripts:/scripts
    command: python /scripts/mvw_atualizacao.py
    depends_on:
      - sienge_main

